DROP TABLE IF EXISTS user  CASCADE;
CREATE TABLE user (
id SERIAL PRIMARY KEY,
first VARCHAR NOT NULL,
last VARCHAR NOT NULL,
email VARCHAR NOT NULL UNIQUE,
imageUrl TEXT,
password VARCHAR NOT NULL
);
